apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: dev
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: node:18-alpine  # Sample Node.js image
        command: ["node", "-e", "require('http').createServer((req, res) => { res.writeHead(200); res.end('Hello from Node!'); }).listen(3000)"]
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"