apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: dev
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: python-app
        image: 975050228815.dkr.ecr.us-east-1.amazonaws.com/python:11
        command: ["python", "-m", "http.server", "8000"]
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"