apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: dev
spec:
  selector:
    app: python-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer