apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: dev
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: react-app
        image: 975050228815.dkr.ecr.us-east-1.amazonaws.com/react:10
        ports:
        - containerPort: 80  # NGINX default
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"